apiVersion: batch/v1
kind: Job
metadata:
  name: alpine
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: alpine
        image: alpine
        command: ["sleep", "30"]
